# -*- coding: utf-8 -*-
"""labelreading.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTJvWhYOexbKLUi3ZdiF36rzXV955Umb
"""

!pip install paddleocr

!pip install imgaug==0.2.5

!pip install paddlepaddle

!pip install gTTS

!git clone https://github.com/PaddlePaddle/PaddleOCR

from paddleocr import PaddleOCR, draw_ocr 
from matplotlib import pyplot as plt 
import cv2 
import os

from paddleocr import PaddleOCR,draw_ocr
ocr = PaddleOCR(lang='en') # need to run only once to download and load model into memory
img_path = '/content/Resource_Label_Group_custom-pharmaceutical-labels-01.jpg'
result = ocr.ocr(img_path, cls=False)
for line in result:
    print(line)

# draw result
from PIL import Image
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='/content/PaddleOCR/doc/fonts/latin.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

ocr_model = PaddleOCR(lang='en')

img_path = '/content/Resource_Label_Group_custom-pharmaceutical-labels-01.jpg'

result = ocr_model.ocr(img_path)

result

result
for res in result:
    print(res[1][0])

boxes = [res[0] for res in result] 
txts = [res[1][0] for res in result]
scores = [res[1][1] for res in result]

txts

font_path = '/content/PaddleOCR/doc/fonts/latin.ttf'

img = cv2.imread(img_path) 


img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(15,15))

annotated = draw_ocr(img, boxes, txts, scores, font_path=font_path) 

plt.imshow(annotated)

print(txts)

my_texts =' '.join(txts)
my_texts

f=open("output.txt","w")
f.write(my_texts)

from gtts import gTTS

f=open("output.txt","r")
tts=f.read()
tt= gTTS(text=tts,lang='en',slow = False)
tt.save("good.mp3")

!pip install gradio

import gradio as gr

import pickle

file = open('model.pkl', 'wb')

pickle.dump(tt, file)

! pip install pdfminer.six

from gtts import gTTS
from pdfminer.high_level import extract_text
import gradio as gr

def pdf_to_text(file_obj):
   text = extract_text(file_obj.name)
   myobj = gTTS(text=tts, lang='en', slow=False)
   myobj.save("output.wav")
   return 'output.wav'

iface = gr.Interface(
   fn = pdf_to_text,
   inputs = 'file',
   outputs = 'audio'
   )
iface.launch()